.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_13 - Debug ]----------"
	@cd "Ejemplo_13" && "$(MAKE)" -f  "Ejemplo_13.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_13 - Debug ]----------"
	@cd "Ejemplo_13" && "$(MAKE)" -f  "Ejemplo_13.mk" clean
