.PHONY: clean All

All:
	@echo "----------Building project:[ PECLBaenaAlonsoJorge - Debug ]----------"
	@cd "PECLBaenaAlonsoJorge" && "$(MAKE)" -f  "PECLBaenaAlonsoJorge.mk"
clean:
	@echo "----------Cleaning project:[ PECLBaenaAlonsoJorge - Debug ]----------"
	@cd "PECLBaenaAlonsoJorge" && "$(MAKE)" -f  "PECLBaenaAlonsoJorge.mk" clean
